---
title: "Empenho: Análise dos Dados, 2018"
author: Dan S. Reznik
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: default
    highlight: default
    code_folding: hide
---

```{r,echo=F}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dpi=96
)
```

```{r setup,message=F}
# Inclusão de pacotes
library(tidyverse)
library(ggthemes)
library(ggforce)
```


## Lê arquivo fonte e renomeia colunas

```{r,cache=T}
# Lê arquivo de execuções 2014-2018
fname_data <- "data/df_all.rds"
df_all <- read_rds(fname_data)
tibble(fname=fname_data,
       lines=nrow(df_all),
       cols=ncol(df_all)) %>%
  knitr::kable()
```

```{r,cache=T}
# Renomeia/seleciona colunas utilizadas
df_all_clean <- df_all %>%
  # era: rename(), select() deixa df menor
  select(ano,
         func_cod=`Função`,
         func=`Nome Função`,
         empenhado=`Valor Empenhado`,
         liquidado=`Valor Liquidado`,
         pago=`Valor Pago`)
df_all_clean %>%
  head(5) %>%
  knitr::kable() %>%
  kableExtra::kable_styling("striped")
```

```{r,cache=T}
# Nomes das funções são únicas por código?
df_all_clean %>%
  count(func_cod,func) %>%
  count(func_cod,name="nn") %>%
  count(nn)
```

## Top 5 funções por valor empenhado

```{r,cache=T}
df_top_funcs_empenhado <- df_all_clean %>%
  group_by(func_cod,func) %>%
  summarize(n=n(),
            empenhado_b=sum(empenhado)/10^9,
            pago_b=sum(pago)/10^9,
            ) %>%
  ungroup() %>%
  arrange(desc(empenhado_b)) %>%
  head(5) %>%
  mutate(rank=row_number(),
         func=func%>%fct_drop%>%fct_inorder,
         func_cod=func_cod%>%fct_drop%>%fct_inorder) %>%
  select(rank,everything())
df_top_funcs_empenhado %>%
  knitr::kable(digits=0) %>%
  kableExtra::kable_styling("striped")
```

### Compara empenhado x liquidado x pago

```{r,cache=T}
df_all_clean %>%
  mutate(func=func%>%fct_reorder(-empenhado,sum)) %>%
  filter(as.integer(func)<6) %>%
  mutate(func=func%>%fct_drop%>%fct_rev) %>% # for coord_flip
  group_by(func) %>%
  # milhoes
  summarize_at(vars(empenhado,liquidado,pago),
               list(~(sum(.)/10^9))) %>%
  gather("tipo","valor",-func) %>%
  mutate(tipo=factor(tipo,levels=c("pago","liquidado","empenhado"))) %>%
  ggplot(aes(func,valor,group=tipo,fill=tipo)) +
  geom_col(position="dodge") +
  coord_flip() +
  labs(title="Valores Totais por Função",
       subtitle="Top 5 por empenho total 2014-8",
       y="Valor (R$ bilhões)") +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.title.y=element_blank())
```

### Faceteando valores por ano

```{r,cache=T}
df_all_clean %>%
  mutate(func=func%>%fct_reorder(-empenhado,sum)) %>%
  filter(as.integer(func)<6) %>%
  mutate(func=func%>%fct_drop%>%fct_rev) %>% # for coord_flip
  group_by(ano,func) %>%
  # milhoes
  summarize_at(vars(empenhado,liquidado,pago),
               list(~(sum(.)/10^9))) %>%
  gather("tipo","valor",-func,-ano) %>%
  mutate(tipo=factor(tipo,levels=c("pago","liquidado","empenhado"))) %>%
  ggplot(aes(func,valor,group=tipo,fill=tipo)) +
  geom_col(position="dodge") +
  coord_flip() +
  labs(title="Valores Totais por Função",
       subtitle="Top 5 por empenho total 2014-8",
       y="Valor (R$ bilhões)") +
  theme(legend.position = "top",
        legend.title = element_blank(),
        axis.title.y=element_blank()) +
  facet_wrap(~ano)
```

```{r,eval=F,include=F}
ggsave("pics/valores_por_funcao_2014-8.png",width=11)
```

### Empenhado vs Pago

```{r,cache=T,include=F}
# to do: ggforce: https://www.data-imaginist.com/2019/the-ggforce-awakens-again/

#df_valores_ggf <- df_all_clean %>%
#  gather("key","value",-func,-ano) %>%
#  filter(key=="empenhado",ano==2017) %>%
#  group_by(ano,func,key)%>%
#  summarize(valor=last(value))

  # geom_mark_ellipse(aes(fill = Species, label = Species)) +
  #geom_mark_circle(aes(ano,valor,
  #                     label=func,
  #                     fill=func),
  #                 data=df_valores_ggf,
  #                 expand=.002,
  #                 label.fontsize=8,
```

```{r,cache=T}
top_levs <- df_top_funcs_empenhado$func%>%levels
df_all_clean_gathered <- df_all_clean %>%
  { suppressWarnings(inner_join(.,df_top_funcs_empenhado%>%
                                  select(rank,func_cod),
                               by="func_cod")) } %>%
  arrange(rank) %>%
  mutate(func=func%>%fct_drop%>%fct_inorder) %>%
  group_by(ano,func) %>%
  summarise(empenhado=sum(empenhado),
            pago=sum(pago)) %>%
  ungroup() %>%
  gather("tipo","valor",empenhado,pago)  %>%
  mutate(func_tipo=func%>%str_c("_",tipo)%>%fct_inorder)
```

```{r,cache=T,message=F}
abbrev_func <- function(s_vec) s_vec %>% str_split(" ") %>% map_chr(~.x%>%str_sub(end=3)%>%str_c(collapse="."))
anos <- df_all_clean_gathered$ano%>%as.character%>%unique
df_all_clean_gathered %>%
  mutate(func=func%>%abbrev_func%>%fct_inorder) %>%
  ggplot(aes(ano,valor/10^9,
             group=func_tipo,
             color=func,linetype=tipo)) +
  geom_line(size=I(1.2)) +
  labs(title="Valor Anual por Função",
       subtitle=sprintf("Anos %s-%s, Top 5",
                        min(anos),max(anos)),
       y = "Valor Total (R$ bilhões)") +
  theme_minimal() +
    theme(legend.position = "bottom",
          legend.title=element_blank(),
          axis.title.x=element_blank())
```

```{r,eval=F,include=F}
ggsave("pics/empenhado vs pago.png",width=11)
```


